package buswinka.aipipeline;
/** Generated by debug-build profile — do not commit this state. */
public final class BuildConfig {
    public static final boolean DEBUG = false;
    private BuildConfig() {}
}
