#!/usr/bin/env bash
# build.sh — single entrypoint for building and releasing ImageJPipelineBuilder
#
# Usage:
#   ./build.sh                      # build only, prompt for version
#   ./build.sh --debug              # build with DEBUG=true, then restore
#   ./build.sh --upload             # build + full GitHub release
#   ./build.sh --upload --notes "Fix crash on startup"
#   ./build.sh --upload --notes-file CHANGES.md
set -euo pipefail

# ---- argument parsing ----
UPLOAD=false
DEBUG=false
RELEASE_NOTES=""
NOTES_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --upload)       UPLOAD=true ;;
    --debug)        DEBUG=true  ;;
    --notes)        RELEASE_NOTES="$2"; shift ;;
    --notes-file)   NOTES_FILE="$2";    shift ;;
    *) echo "Unknown argument: $1"; echo ""; echo "Usage: $0 [--upload] [--debug] [--notes \"text\"] [--notes-file FILE]"; exit 1 ;;
  esac
  shift
done

# ---- version negotiation ----
CURRENT=$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout 2>/dev/null | sed 's/-SNAPSHOT//')

IFS='.' read -r MAJOR MINOR PATCH <<< "$CURRENT"
if   [ "$PATCH" -lt 99 ]; then NEXT="$MAJOR.$MINOR.$((PATCH + 1))"
elif [ "$MINOR" -lt 99 ]; then NEXT="$MAJOR.$((MINOR + 1)).0"
else                            NEXT="$((MAJOR + 1)).0.0"
fi

read -rp "Current: $CURRENT  New [$NEXT]: " INPUT
VERSION="${INPUT:-$NEXT}"

echo ""
if [ "$DEBUG" = true ]; then
  echo "Building ImageJPipelineBuilder.jar (version $VERSION) [DEBUG MODE] ..."
else
  echo "Building ImageJPipelineBuilder.jar (version $VERSION) ..."
fi
echo ""

# ---- updater source path ----
UPDATER_SRC="src/main/java/buswinka/aipipeline/PluginUpdater.java"

# ---- pre-build: patch version strings in source & POM ----
mvn -q versions:set -DnewVersion="$VERSION" -DgenerateBackupPoms=false

# Update PluginUpdater.CURRENT_VERSION so the built JAR knows its own version
sed -i '' \
  "s/public static final String CURRENT_VERSION = \"[^\"]*\";/public static final String CURRENT_VERSION = \"$VERSION\";/" \
  "$UPDATER_SRC"

# ---- build ----
MVN_PROFILES=""
[ "$DEBUG" = true ] && MVN_PROFILES="-Pdebug-build"

restore_on_failure() {
  echo ""
  echo "Build failed. Restoring version $CURRENT in pom.xml and $UPDATER_SRC."
  mvn -q versions:set -DnewVersion="$CURRENT" -DgenerateBackupPoms=false
  sed -i '' \
    "s/public static final String CURRENT_VERSION = \"[^\"]*\";/public static final String CURRENT_VERSION = \"$CURRENT\";/" \
    "$UPDATER_SRC"
  if [ "$DEBUG" = true ]; then
    restore_build_config
  fi
}

restore_build_config() {
  echo "Restoring BuildConfig.java to DEBUG=false."
  cat > src/main/java/buswinka/aipipeline/BuildConfig.java <<'JAVAEOF'
package buswinka.aipipeline;
/** Generated by debug-build profile — do not commit this state. */
public final class BuildConfig {
    public static final boolean DEBUG = false;
    private BuildConfig() {}
}
JAVAEOF
}

if ! mvn clean install $MVN_PROFILES; then
  restore_on_failure
  exit 1
fi

[ "$DEBUG" = true ] && restore_build_config

JAR="target/ImageJPipelineBuilder.jar"
echo ""
echo "Built $JAR (version $VERSION)"

# ---- upload / release ----
if [ "$UPLOAD" = false ]; then
  exit 0
fi

# Require gh CLI
if ! command -v gh &>/dev/null; then
  echo "Error: 'gh' (GitHub CLI) is not installed. Install it and run 'gh auth login' first."
  exit 1
fi

# Require a clean working tree (only our own staged changes are allowed)
if [ -n "$(git status --porcelain | grep -v '^[AM]  ' | grep -v '^??' )" ]; then
  echo ""
  echo "Warning: working tree has unexpected changes. Proceeding anyway."
fi

# Compute SHA-256 of the JAR
echo ""
echo "Computing SHA-256..."
SHA256=$(shasum -a 256 "$JAR" | awk '{print $1}')
echo "  SHA-256: $SHA256"

# Release asset download URL (GitHub Releases direct asset — not rate-limited)
REPO=$(git remote get-url origin | sed 's|.*github\.com[:/]\(.*\)\.git|\1|; s|.*github\.com[:/]\(.*\)|\1|')
RELEASE_TAG="v$VERSION"
ASSET_URL="https://github.com/$REPO/releases/download/$RELEASE_TAG/ImageJPipelineBuilder.jar"

# Write docs/latest.json
echo "Writing docs/latest.json..."
mkdir -p docs
cat > docs/latest.json <<JSONEOF
{
  "version": "$VERSION",
  "url": "$ASSET_URL",
  "sha256": "$SHA256",
  "mandatory": false,
  "release_notes": "${RELEASE_NOTES}"
}
JSONEOF
echo "  -> docs/latest.json"

# Commit: pom.xml + PluginUpdater.java + docs/latest.json
echo ""
echo "Committing release files..."
git add pom.xml "$UPDATER_SRC" docs/latest.json
git commit -m "release: v$VERSION"

# Tag
git tag "$RELEASE_TAG"
echo "Tagged $RELEASE_TAG"

# Push commits and tag
echo "Pushing to origin..."
git push
git push origin "$RELEASE_TAG"

# Build gh release notes string
GH_NOTES_ARGS=()
if [ -n "$NOTES_FILE" ]; then
  GH_NOTES_ARGS+=(--notes-file "$NOTES_FILE")
elif [ -n "$RELEASE_NOTES" ]; then
  GH_NOTES_ARGS+=(--notes "$RELEASE_NOTES")
else
  GH_NOTES_ARGS+=(--generate-notes)
fi

# Create GitHub Release and upload JAR
echo "Creating GitHub Release $RELEASE_TAG..."
gh release create "$RELEASE_TAG" "$JAR" \
  --title "$RELEASE_TAG" \
  "${GH_NOTES_ARGS[@]}"

echo ""
echo "Release complete: https://github.com/$REPO/releases/tag/$RELEASE_TAG"
echo "Manifest:         https://$(echo "$REPO" | cut -d/ -f1).github.io/$(echo "$REPO" | cut -d/ -f2)/latest.json"
